// Sample data for comments
export const commentsData = [
  {
    id: 1,
    content:
      "This is such a beautiful story! It reminds me of my own grandmother's stories about her childhood in the countryside. The details you've included really bring it to life.",
    author: "Sarah Johnson",
    authorEmail: "sarah.j@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-15T14:30:00",
    status: "approved",
    story: "Family Vacation Memories",
    flags: 0,
    likes: 12,
    replies: 2,
  },
  {
    id: 2,
    content:
      "I'm not sure if this is historically accurate. My grandfather told me a different version of these events during the war. Perhaps there are regional differences in how these stories were passed down?",
    author: "Michael Chen",
    authorEmail: "m.chen@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-14T09:15:00",
    status: "pending",
    story: "World War II Memories",
    flags: 0,
    likes: 3,
    replies: 0,
  },
  {
    id: 3,
    content:
      "This content contains inappropriate language and references that should not be included in a family-friendly platform. Please review and remove this comment.",
    author: "Anonymous User",
    authorEmail: "anonymous@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-13T22:45:00",
    status: "flagged",
    story: "College Years",
    flags: 3,
    likes: 0,
    replies: 1,
  },
  {
    id: 4,
    content:
      "Thank you for sharing this beautiful memory. It brought tears to my eyes. My grandmother used to make the exact same recipe, and the smell of it baking would fill the entire house with warmth.",
    author: "Emily Rodriguez",
    authorEmail: "emily.r@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-12T16:20:00",
    status: "approved",
    story: "Grandmother's Recipe",
    flags: 0,
    likes: 8,
    replies: 3,
  },
  {
    id: 5,
    content:
      "I disagree with some points in this story, but I appreciate the perspective. It's important to remember that political memories are often colored by personal experiences and beliefs.",
    author: "David Wilson",
    authorEmail: "d.wilson@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-11T11:05:00",
    status: "pending",
    story: "Political Memories",
    flags: 1,
    likes: 2,
    replies: 0,
  },
  {
    id: 6,
    content:
      "Check out my website at www.spam-site.com for amazing deals! 50% off everything today only! Click now before the offer expires!",
    author: "Robert Smith",
    authorEmail: "robert@spam-site.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-10T08:30:00",
    status: "spam",
    story: "High School Memories",
    flags: 2,
    likes: 0,
    replies: 0,
  },
  {
    id: 7,
    content:
      "I love how you've captured the essence of that era. The details are so vivid! The music, the fashion, the cultural references - it all takes me right back to my own childhood in the 60s.",
    author: "Jennifer Lee",
    authorEmail: "jen.lee@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-09T19:45:00",
    status: "approved",
    story: "1960s Childhood",
    flags: 0,
    likes: 15,
    replies: 4,
  },
  {
    id: 8,
    content:
      "Could you share more details about the location? I think my family visited the same place in the summer of '85. Was this near the old lighthouse on the north shore?",
    author: "Thomas Brown",
    authorEmail: "t.brown@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-08T13:20:00",
    status: "pending",
    story: "Summer Vacation 1985",
    flags: 0,
    likes: 5,
    replies: 1,
  },
  {
    id: 9,
    content:
      "This story contains factual inaccuracies. The event described couldn't have happened in 1972 because the building wasn't constructed until 1975. Please verify your timeline.",
    author: "History Buff",
    authorEmail: "history@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-07T10:15:00",
    status: "approved",
    story: "Downtown Memories",
    flags: 0,
    likes: 3,
    replies: 2,
  },
  {
    id: 10,
    content:
      "Your story about the family reunion brought back so many memories. We used to have similar gatherings every summer. Those traditions are so important to maintain.",
    author: "Family Person",
    authorEmail: "family@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-06T15:30:00",
    status: "approved",
    story: "Family Reunion",
    flags: 0,
    likes: 7,
    replies: 1,
  },
  {
    id: 11,
    content:
      "This comment contains personal information including phone numbers and addresses that should not be shared publicly. Please remove this content immediately.",
    author: "Privacy Concerned",
    authorEmail: "privacy@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-05T09:45:00",
    status: "flagged",
    story: "Neighborhood Stories",
    flags: 4,
    likes: 0,
    replies: 0,
  },
  {
    id: 12,
    content:
      "The photographs in this story are absolutely stunning. Did you use any special restoration techniques? I have some old family photos I'd love to restore similarly.",
    author: "Photo Enthusiast",
    authorEmail: "photos@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-04T14:20:00",
    status: "approved",
    story: "Family Album",
    flags: 0,
    likes: 9,
    replies: 2,
  },
]

// Sample data for replies
export const repliesData = [
  {
    id: 101,
    parentId: 1,
    content: "Thank you so much! I'm glad it resonated with you. My grandmother was an amazing storyteller.",
    author: "Memory Keeper",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-15T15:10:00",
    isAuthor: true,
  },
  {
    id: 102,
    parentId: 1,
    content: "Would you be willing to share some of your grandmother's stories too? I'd love to hear them!",
    author: "Memory Keeper",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-15T15:12:00",
    isAuthor: true,
  },
  {
    id: 103,
    parentId: 3,
    content: "Thank you for flagging this. We've reviewed the content and taken appropriate action.",
    author: "Moderator",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-13T23:15:00",
    isAuthor: false,
    isModerator: true,
  },
  {
    id: 104,
    parentId: 4,
    content: "I'm touched that it moved you so much. These family recipes are such precious treasures, aren't they?",
    author: "Memory Keeper",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-12T17:05:00",
    isAuthor: true,
  },
  {
    id: 105,
    parentId: 4,
    content: "Did your grandmother have a similar recipe? I'd love to compare notes!",
    author: "Memory Keeper",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-12T17:08:00",
    isAuthor: true,
  },
  {
    id: 106,
    parentId: 4,
    content: "Yes, she did! Her secret ingredient was a pinch of cardamom. It made all the difference.",
    author: "Emily Rodriguez",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-12T18:30:00",
    isAuthor: false,
  },
  {
    id: 107,
    parentId: 7,
    content: "Thank you! I spent a lot of time going through old photos to get the details right.",
    author: "Memory Keeper",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-09T20:15:00",
    isAuthor: true,
  },
  {
    id: 108,
    parentId: 7,
    content: "The colors in those old Kodak photos really capture the mood of that time, don't they?",
    author: "Jennifer Lee",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-09T20:45:00",
    isAuthor: false,
  },
  {
    id: 109,
    parentId: 7,
    content: "Did you use any special techniques to restore the old photos? They look amazing.",
    author: "PhotoEnthusiast",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-10T09:30:00",
    isAuthor: false,
  },
  {
    id: 110,
    parentId: 7,
    content: "I'd love to know more about the music you mentioned from that era. Do you have a playlist?",
    author: "MusicLover",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-10T11:15:00",
    isAuthor: false,
  },
  {
    id: 111,
    parentId: 8,
    content: "It was at Lake Winnipesaukee in New Hampshire. Did your family visit there too?",
    author: "Memory Keeper",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-08T14:10:00",
    isAuthor: true,
  },
  {
    id: 112,
    parentId: 9,
    content:
      "Thank you for pointing this out. You're right about the timeline. I'll update the story with the correct dates.",
    author: "Memory Keeper",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-07T11:30:00",
    isAuthor: true,
  },
  {
    id: 113,
    parentId: 9,
    content: "I have some historical photos of the building construction if you'd like to include them in your story.",
    author: "History Buff",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-07T12:45:00",
    isAuthor: false,
  },
  {
    id: 114,
    parentId: 10,
    content: "Family traditions are so important! Do you still maintain any of those reunion traditions today?",
    author: "Memory Keeper",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-06T16:15:00",
    isAuthor: true,
  },
  {
    id: 115,
    parentId: 12,
    content:
      "I used a combination of Photoshop and some AI restoration tools. I'd be happy to share my process with you!",
    author: "Memory Keeper",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-04T15:00:00",
    isAuthor: true,
  },
  {
    id: 116,
    parentId: 12,
    content: "That would be wonderful! I have a box of old photos from the 1940s that need some love.",
    author: "Photo Enthusiast",
    avatar: "/placeholder.svg?height=40&width=40",
    date: "2024-03-04T15:30:00",
    isAuthor: false,
  },
]

// Statistics for the dashboard
export function getCommentStatistics() {
  return {
    totalComments: commentsData.length,
    approvedComments: commentsData.filter((c) => c.status === "approved").length,
    pendingComments: commentsData.filter((c) => c.status === "pending").length,
    flaggedComments: commentsData.filter((c) => c.status === "flagged").length,
    spamComments: commentsData.filter((c) => c.status === "spam").length,
    totalLikes: commentsData.reduce((sum, comment) => sum + comment.likes, 0),
    totalReplies: commentsData.reduce((sum, comment) => sum + comment.replies, 0),
    engagementRate: 68,
    averageResponseTime: "4.2 hours",
  }
}

